### ISSUE TITLE
Verständnisfrage

### ISSUE THREAD

**Issue by Pebesch** [Pebesch/webcl-hs20-2#4]
@Dierk
Habe ich das richtig verstanden, dass Observable ein Interface ist und Attribute die konkrete Implementierung davon?

**Comment by Dierk** [comment]
@Pebesch 
Nein, Attribute _verwenden_ Observables - für den value aber auch für andere Informationen an die sich der View per Observable binden will: validity, enabled, editable, u.s.w.

Es ist sicher hilfreich, sich den code von Woche 2 und 3 in dieser Hinsicht anzuschauen.
